variable "organization_id"      { type = string }
# variable "folder_id"            { type = string }
variable "project_name"         { type = string }
variable "project_id"           { type = string }
variable "billing_account"      { type = string }
variable "gcp_region"           { type = string }
# variable "usage_bucket_name"    { type = string }
# variable "usage_bucket_prefix"  { type = string }
variable "apis"                 { type = list(string) }
